version: "3.2"

services:

  traefik:
    image: traefik:2.2
    restart: always
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=${APP_DEBUG}
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
       ACME
      - --certificatesresolvers.primary.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.primary.acme.storage=acme.json
      - --certificatesresolvers.primary.acme.httpchallenge.entrypoint=web
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certResolver=primary"
    networks:
      - seat-network
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
  
  saidthefox.js:
    build:
      context: ./saidthefox.com
      dockerfile: Dockerfile-saidthefoxjs
    container_name: saidthefox.js
    command: npm start
    ports:
      -  "3006:3006"
    networks:
      - seat-network

  saidthefox.com:
    build:
      context: ./saidthefox.com-nginx-docker
      dockerfile: Dockerfile-saidthefox-nginx
    container_name: saidthefox.com
    expose:
     - 80
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.saidthefox.rule=Host(`saidthefox.com`)"
     - "traefik.http.routers.saidthefox.entrypoints=websecure"
     - "traefik.http.routers.saidthefox.tls.certresolver=primary"
    networks:
     - seat-network

  live.js:
    build:
      context: ./live.saidthefox.com
      dockerfile: Dockerfile-livejs
    container_name: live.js
    command: node main.js
    volumes:
      - /usr/app/node_modules
      - /usr/app/html
    ports:
      - "3001:3001"
    networks:
      - seat-network

  live.saidthefox.com:
    build:
      context: ./live.saidthefox.com-nginx-docker
      dockerfile: Dockerfile-live.nginx
    container_name: live.saidthefox.com
    expose:
     - 80
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.live.rule=Host(`live.saidthefox.com`)"
     - "traefik.http.routers.live.entrypoints=websecure"
     - "traefik.http.routers.live.tls.certresolver=primary"
    networks:
     - seat-network

  book.js:
    build:
      context: ./book.saidthefox.com
      dockerfile: Dockerfile-bookjs
    container_name: book.js
    command: npm start
    ports:
      - "1234:1234"
    networks:
      - seat-network

  book.saidthefox.com:
    build:
      context: ./book.saidthefox.com-nginx-docker
      dockerfile: Dockerfile-book.nginx
    container_name: book.saidthefox.com
    expose:
     - 80
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.book.rule=Host(`book.saidthefox.com`)"
     - "traefik.http.routers.book.entrypoints=websecure"
     - "traefik.http.routers.book.tls.certresolver=primary"
    networks:
     - seat-network

networks:
    seat-network:
